# Generated by Django 4.0.3 on 2022-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='todolistitem',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
