# Generated by Django 4.0.3 on 2022-04-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0002_alter_todolist_options_alter_todolistitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='to_do_list',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.DeleteModel(
            name='ToDoListItem',
        ),
    ]
