# Generated by Django 4.0.3 on 2022-04-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoListItem',
            new_name='Task',
        ),
    ]
